-- PostgreSQL. Apply once to a new schema; no DROP or destructive cleanup.
BEGIN;
CREATE SCHEMA IF NOT EXISTS mesto_assessment;
SET LOCAL search_path TO mesto_assessment, pg_catalog;
SET LOCAL standard_conforming_strings = on;

CREATE TABLE specializations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code TEXT NOT NULL UNIQUE CHECK (code <> ''),
 name TEXT NOT NULL, description TEXT NOT NULL,
 direction_code TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE grades (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code TEXT NOT NULL UNIQUE CHECK (code <> ''),
 name TEXT NOT NULL, sort_order INTEGER NOT NULL CHECK (sort_order > 0)
);
CREATE TABLE competencies (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code TEXT NOT NULL UNIQUE CHECK (code <> ''),
 name TEXT NOT NULL, description TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE technologies (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code TEXT NOT NULL UNIQUE CHECK (code <> ''),
 name TEXT NOT NULL, kind TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE specialization_competencies (
 specialization_id BIGINT NOT NULL REFERENCES specializations(id) ON DELETE RESTRICT,
 competency_id BIGINT NOT NULL REFERENCES competencies(id) ON DELETE RESTRICT,
 relevance_description TEXT NOT NULL,
 PRIMARY KEY (specialization_id, competency_id)
);
CREATE INDEX specialization_competencies_by_competency ON specialization_competencies(competency_id);
CREATE TABLE criteria (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code TEXT NOT NULL CHECK (code <> ''), version INTEGER NOT NULL CHECK (version > 0),
 name TEXT NOT NULL, description TEXT NOT NULL,
 check_templates JSONB NOT NULL CHECK (jsonb_typeof(check_templates) = 'array'),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE (code, version)
);
CREATE UNIQUE INDEX criteria_one_active_version ON criteria(code) WHERE active;
CREATE TABLE criterion_competencies (
 criterion_id BIGINT NOT NULL REFERENCES criteria(id) ON DELETE RESTRICT,
 competency_id BIGINT NOT NULL REFERENCES competencies(id) ON DELETE RESTRICT,
 active BOOLEAN NOT NULL DEFAULT TRUE, scope_note TEXT NOT NULL,
 PRIMARY KEY (criterion_id, competency_id)
);
CREATE INDEX criterion_competencies_by_competency ON criterion_competencies(competency_id) WHERE active;
CREATE TABLE tests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 -- External account ID. No account table exists in this standalone export.
 candidate_id TEXT NOT NULL CHECK (candidate_id <> ''),
 request_key TEXT NOT NULL CHECK (request_key <> ''),
 specialization_id BIGINT NOT NULL REFERENCES specializations(id) ON DELETE RESTRICT,
 declared_grade_id BIGINT NOT NULL REFERENCES grades(id) ON DELETE RESTRICT,
 competency_ids JSONB NOT NULL CHECK (jsonb_typeof(competency_ids) = 'array' AND jsonb_array_length(competency_ids) BETWEEN 1 AND 3),
 technology_context JSONB NOT NULL CHECK (jsonb_typeof(technology_context) = 'array'),
 criteria_snapshot JSONB NOT NULL CHECK (jsonb_typeof(criteria_snapshot) = 'array' AND jsonb_array_length(criteria_snapshot) = jsonb_array_length(competency_ids)),
 assignment JSONB CHECK (assignment IS NULL OR jsonb_typeof(assignment) = 'object'),
 status TEXT NOT NULL CHECK (status IN ('generating','ready','generation_failed')),
 generation_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(generation_metadata) = 'object'),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE (candidate_id, request_key), UNIQUE (id, candidate_id),
 CHECK (status <> 'ready' OR assignment IS NOT NULL)
);
CREATE INDEX tests_by_candidate ON tests(candidate_id, created_at);
CREATE TABLE test_attempts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 candidate_id TEXT NOT NULL CHECK (candidate_id <> ''), test_id BIGINT NOT NULL,
 answer JSONB CHECK (answer IS NULL OR jsonb_typeof(answer) = 'object'),
 evaluation JSONB CHECK (evaluation IS NULL OR jsonb_typeof(evaluation) = 'object'),
 status TEXT NOT NULL CHECK (status IN ('in_progress','evaluating','preliminary','awaiting_review','verified','evaluation_failed')),
 started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, submitted_at TIMESTAMPTZ,
 FOREIGN KEY (test_id, candidate_id) REFERENCES tests(id, candidate_id) ON DELETE RESTRICT,
 UNIQUE (test_id), CHECK (submitted_at IS NULL OR submitted_at >= started_at)
);
CREATE INDEX test_attempts_by_candidate ON test_attempts(candidate_id, started_at);
COMMIT;
